### PR TITLE
Dns

### PR DESCRIPTION
**Pull request by jngermon**

### CODE REVIEW

**Comment by mykiwi** [comment]
Alternative: https://github.com/jderusse/docker-dns-gen

**Comment by greg0ire** [comment]
@romqin How does it compare to dnsdock ?

**Comment by greg0ire** [comment]
@romqin I'll have a look at it this week-end

**Comment by jderusse** [comment]
dnsdock looks more configurable than dns-gen (`--http`, `--ttl`).
but dns-gen is more flexible in naming (it does not impose the format `<anything>.<container-name>.<image-name>.<environment>.<domain>`, you can use `app.docker` if you want)
and dns-gen does not reinvent the weel. It rely on dnsmasq to serve queries which's really stable and robust.

NB: Don't read the last part of the dns-gen's README (aka `bonus` thing) it's outdated and uggly...

**Comment by greg0ire** [comment]
Thanks for the explanation. If dnsdock turns out to be unstable, we'll know where to look.

**Comment by greg0ire** [comment]
> but dns-gen is more flexible in naming

Not sure that bit is really true : you can alias containers with the `DNSDOCK_ALIAS` environment variable.

**Pull request merged**
