### PR TITLE
split the php image into three images

### PR DESCRIPTION
**Pull request by greg0ire**
This should make tests easier to run, because the console server will
able to depend on, and resolve the webserver, which can be necessary
when using Guzzle to test APIs.
Moreover, it separates the nice and clean php-fpm definition from the
quite dirty console definition, that has nodejs, npm, zsh, and will
probably have more development-related packages in the future.
Repetition is avoided with the php image, that is not intended to be run
at all, but to server as a basis for the 2 other images.

### CODE REVIEW

**Comment by greg0ire** [comment]
@jngermon what do you think ?

**Comment by jngermon** [comment]
I think that is a good idea. I was afraid about the differents versions of PHP that the two images will used. But you've based the two images on `greg0ire/php` so ... it's perfect.
Did you tagged the old `greg0ire/php` image ? To enable the old project who used this can continue.

**Comment by jngermon** [comment]
Sorry, I have just seen the release that you do... it's perfect for me.

**Comment by greg0ire** [comment]
Glad to hear that! I am going to check the README (I think I might have to change some things in there), and then I'll merge!

**Pull request merged**
